In [6]:
def x():
    result,temp=0,0
    result=int(input('수 입력:'))
    while True:
        temp=int(result%10)
        result=int(result/10)
        print(temp,end='')
        if not result:
            break
    print('종료')

In [ ]:
print('프로그램 시작')
print('프로그램 종료')

In [12]:
from reverse1 import x


In [14]:
x()

dasd:1
1ddddd


In [19]:
def sel_machine():
    sel=0
    sel=int(input('음료 선택 \n1.콜라\n2.핫6\n3.포카리\n입력:'))
    if sel==1:
        print('콜라')
    elif sel==2:
        print('핫식스')
    elif sel==3:
        print('포카리')
    else:print('만들어 드세요')
    
    if sel>=1 and sel<=3:
        print('맛있게 드세요')
sel_machine()

음료 선택 
1.콜라
2.핫6
3.포카리
입력:4
만들어 드세요


In [20]:
import numpy as np
np.random.random((2,5))

array([[0.51575304, 0.08630789, 0.18742856, 0.74348964, 0.77907574],
       [0.60174651, 0.09088495, 0.64333362, 0.54076177, 0.68582997]])

In [21]:
len('sdsd')

4

In [23]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [24]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [25]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
np.empty([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
a=np.zeros((2,3))

In [37]:
a.astype(np.int64)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [38]:
a=np.full((2,3),3)

In [42]:
a.sum(axis=0)

array([6, 6, 6])

In [44]:
a.reshape(3,2)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [45]:
a.resize(2,3)

In [47]:
a.reshape(3,2)

array([[3, 3],
       [3, 3],
       [3, 3]])

In [49]:
b=np.full((2,3),4)

In [53]:
np.concatenate((a,b),axis=0)

array([[3, 3, 3],
       [3, 3, 3],
       [4, 4, 4],
       [4, 4, 4]])

In [60]:
np.random.random(3)

array([0.38118027, 0.50683923, 0.28371544])

In [61]:
def showAvg(a,b,c):
    print('{}와 {}의 평균'.format(a,b))
    print('값은 {}입니다'.format(round(c,1)))

def avg(j,k):
    total=j+k
    f=total/2
    return f

i=2
j=3
f=avg(i,j)
showAvg(i,j,f)

2와 3의 평균
값은 2.5입니다


In [62]:
def func2(a,b):
    a+=5
    b*=10
    print('func2:a={},b={}'.format(a,b))
def func1():
    a=5
    b=10
    func2(a,b)
    print('func1 : a={},b={}'.format(a,b))
func1()

func2:a=10,b=100
func1 : a=5,b=10


In [66]:
def aa(a):
    if a==1:
        return
        print('1입력')
    print('다음 문장 실행')

a=aa(1)
print(a)



None


In [70]:
def move():
    pass
def attack():
    pass
def defense():
    pass

move()
attack()
defense()

In [72]:
def a(a):
    if a==1:
        pass
    else:
        print('1이 아니에요')
a(2)



1이 아니에요


In [ ]:
def _1(value):
    if value%2==0:
        print('짝수입니다')
    else:
        print('홀수입니다')
    return value

def _2(value):
    if value%3==0:
        print('3의 배수입니다')
    else:
        print('3의 배수가 아닙니다')
    return value

def _3(value):
    while True:
    b=int(value%10)
    value=int(value//10)
    return b

def sel_machine(sel):
    if sel==1:
        print('콜라')
    elif sel==2:
        print('핫식스')
    elif sel==3:
        print('포카리')
    else:print('만들어 드세요')
    
    if sel>=1 and sel<=3:
        print('맛있게 드세요')
sel=int(input('음료 선택 \n1.콜라\n2.핫6\n3.포카리\n입력:'))
    
    

In [73]:
def func1():
    a=100
    print(a)
def func2():
    a=200
    print(a)
    
func1()
func2()

100
200


In [74]:
def func1():
    
    print(a)
def func2():

    print(a)
    
a=200
func1()
func2()

200
200


In [75]:
def func1():
    a=123
    print(a)
def func2():
    print(a)
    
a=200
func1()
func2()

123
200


In [77]:
def func1():
    global a
    a=1222
    print(a)
def func2():
    print(a)

a=200
func2()
func1()
func2()

200
1222
1222


In [92]:
num=10
sum_=0

def display():
    sumFunc()
    print(sum_)
def sumFunc():
    global sum_
    for i in range(num+1):
        sum_+=i
display()


55


In [94]:
def sum_func(x1,x2,x3=100):
    result=0
    result=x1+x2+x3
    return result
def display():
    Sum=0
    a,b,c=10,20,30
    Sum=sum_func(a,b)
    print(Sum)
    Sum=sum_func(a,b,c)
    print(Sum)
display()

130
60


In [98]:
def alpha(day=30,time=8,won=8500):
    result=day*time*8500
    return result
def display():
    num=int(input('1.기본급\n2.일한 날짜 입력\n'))
    if num==1:
        result=alpha()
    elif num==2:
        day=int(input('일한 날짜 입력(몇일):'))
        result=alpha(day)
    print('당신의 급여:{}원 입니다'.format(result))
display()

1.기본급
2.일한 날짜 입력
2
일한 날짜 입력(몇일):12
당신의 급여:816000원 입니다


In [100]:
def sum_func(*par):
    result=0
    print('type:',type(par))
    print(par)
    for num in par:
        result=result+num
        print(num)
    return result
sum_=0
sum_=sum_func(10,20)
print(sum_)
sum_=sum_func(10,20,30,40)
print(sum_)

type: <class 'tuple'>
(10, 20)
10
20
30
type: <class 'tuple'>
(10, 20, 30, 40)
10
20
30
40
100


In [103]:
def dic_func(**par):
    print(type(par))
    for k in par.keys():
        print(k,par[k])
dic_func(a=123,b=8,c=123555)

<class 'dict'>
a 123
b 8
c 123555


In [104]:
def change(a,b,c):
    return a+10,b+20,c+30
a,b,c=change(10,20,30)
d=change(10,20,30)
print(a,b,c)
print(d,type(d))

20 40 60
(20, 40, 60) <class 'tuple'>


In [105]:
def swap(x,y):
    return y,x
a=10
b=20
print(a,b)
a,b=swap(a,b)
print(a,b)

10 20
20 10


In [109]:
swap=lambda a,b:[b,a]
a=swap(10,20)
print(a)

[20, 10]


In [110]:
lam=lambda a : a*10
hap=lambda a,b: a+b
nodata=lambda : print('인자값 없는 람다')
print(lam(10))
print(hap(5,10))
nodata()

100
15
인자값 없는 람다


In [114]:
add_=lambda a,b : a+b
sub_=lambda a,b : a-b
mul_=lambda a,b : a*b
div_=lambda a,b : a/b

def _2(std_fee=500):
    print('1. 환승안함')
    print('2. 환승 함')
    print('3. 장거리')
    
     
    cho=int(input('번호를 선택하시오:'))
    if cho==1:
        print('요금은 {} 입니다'.format(std_fee))
    
    elif cho==2:
        des=input('목적지를 입력하시오:')
        count_trans=int(input('환승 수를 입력하시오:'))
        amount=std_fee
        for i in range(count_trans):
            amount*=2
        if amount>10000:
            print('{}까지 요금: 10000원입니다'.format(des))
        else:
            print('{}까지 요금: {}원 입니다'.format(des,amount))
        
    
    elif cho==3:
        print('장거리 요금: 10000원입니다')

In [118]:
_2()

1. 환승안함
2. 환승 함
3. 장거리
번호를 선택하시오:3
장거리 요금: 10000원입니다
